-- DROP DATABASE IF EXISTS Car_dealership;

CREATE DATABASE Car_dealership;


-- TABLE 1
-- DEALERSHIP

CREATE TABLE Dealership (
DealerShipID INT PRIMARY KEY AUTO_INCREMENT ,
Name VARCHAR(50)  NOT NULL,
Address VARCHAR(50) NOT NULL,
Phone VARCHAR(50) NOT NULL
);

INSERT INTO Dealership
VALUES(1, 'QUEENS AUTO MALL' , '56-23 Grandprix rd', '929-340-0898'),
	  (2, 'LUXARY AUTO' , '179-32 GreenWood rd', '646-098-123'),
      (3, 'HILLSIDE HONDA' , '145-45 Hillside Ave' , '718-234-3456');


-- TABLE 2 
-- VEHICLES

CREATE TABLE Vehicles(
VIN INT PRIMARY KEY NOT NULL,
Make VARCHAR(20) NOT NULL,
Model VARCHAR(15) NOT NULL,
Year INT NOT NULL,
Price Numeric(10,2) NOT NULL,
Sold BIT
);

INSERT INTO VEHICLES
VAlUES(252509 , 'BMW' , '330CI' , 2004 , 4500 , TRUE),
	  (343409 , 'BMW' , '750LI' , 2018 , 65000, FALSE),
      (454509 , 'BMW' , 'M3 CSL' , 2022 , 109000, FALSE);

-- TABLE 3
-- INVENTORY(TRACK WHICH DEALERSHIP HAS THE VEHICLE)
CREATE TABLE Inventory(
DealerShipID INT NOT NULL,
VIN INT NOT NULL,
FOREIGN KEY (DealerShipID) REFERENCES Dealership(DealerShipID),
FOREIGN KEY (VIN) REFERENCES Vehicles(VIN)
);

INSERT INTO INVENTORY
VALUES  (1, 252509),
		(2, 343409),
        (3, 454509);
		


-- TABLE 4 
-- SALES-CONTRACT
CREATE TABLE Sales_Contract(
SaleID INT PRIMARY KEY AUTO_INCREMENT,
Customer_Name VARCHAR(40) NOT NULL,
Customer_Email VARCHAR(35),
Date_Contract DATE NOT NULL,
VIN INT NOT NULL,
Price INT NOT NULL,
FOREIGN KEY (VIN) REFERENCES Vehicles(VIN)
);

INSERT INTO Sales_Contract(

);

